version: '3.8'

services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=final
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=030119030
    volumes:
      - db_data:/bitnami/mariadb

  final:
    image: bitnami/final:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=030119030
      - MARIADB_DATABASE=final
    volumes:
      - drupal_data:/bitnami/final

  webserver:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - final
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - drupal_data:/bitnami/final

  certbot:
    image: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

nginx:
    images : nginx:latest
    ports:
        -'80:80'
    volumes:
        -./nginx
        -/nginx
